# Shopify-Grist Synchronization Configuration

# Shopify API configuration
shopify:
  store_url: "your-store.myshopify.com"
  api_key: "your_api_key"
  api_secret: "your_api_secret"
  access_token: "your_access_token"
  api_version: "2023-07"

# Grist API configuration
grist:
  api_key: "your_grist_api_key"
  doc_id: "your_document_id"
  workspace_id: "your_workspace_id"

# Sync settings
sync:
  # Default sync interval in minutes (for continuous mode)
  interval: 15
  
  # Default sync mode (once or continuous)
  mode: "once"
  
  # Conflict resolution priority (shopify or grist)
  # When the same field is modified in both systems, which one takes precedence
  conflict_priority: "shopify"
  
  # Resources to sync (comment out to disable)
  resources:
    - products
    - inventory
    - orders
    - collections
  
  # Rate limiting to avoid API throttling
  rate_limits:
    shopify_calls_per_minute: 40
    grist_calls_per_minute: 100

# Notification settings
notifications:
  # Email notifications for sync errors
  email:
    enabled: false
    smtp_server: "smtp.example.com"
    smtp_port: 587
    smtp_user: "user@example.com"
    smtp_password: "your_password"
    recipients:
      - "admin@example.com"
  
  # Slack notifications for sync errors
  slack:
    enabled: false
    webhook_url: "https://hooks.slack.com/services/your/webhook/url"
    channel: "#sync-notifications"

# Logging configuration
logging:
  # Log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  level: "INFO"
  
  # Log file path
  file: "sync.log"
  
  # Log rotation settings
  max_size_mb: 10
  backup_count: 5 